services:
  db:
    image: postgres:15.7-alpine
    container_name: adm-videos-db
    environment:
      - POSTGRES_USER=videos
      - POSTGRES_PASSWORD=videos
      - POSTGRES_DB=adm_videos_db
    ports:
      - 5439:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U videos -d adm_videos_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    depends_on:
      db:
        condition: service_healthy
    container_name: catalogo-app
    ports:
      - 7777:4000    