version: "3.7"

services:
  db:
    image: postgres:15.7-alpine
    container_name: adm-videos-db
    environment:
      - POSTGRES_USER=videos
      - POSTGRES_PASSWORD=videos
      - POSTGRES_DB=adm_videos_db
    ports:
      - 5439:5432