POST http://localhost:4000/v1/categories HTTP/1.1
Host: localhost:4000
Content-Type: application/json

{
    "name": "Drinks",
    "description": "drinks description"
}

###

GET http://localhost:4000/v1/categories/1 HTTP/1.1
Host: localhost:4000

###

POST http://localhost:4000/v1/categories/1/activate HTTP/1.1
Host: localhost:4000

###
POST http://localhost:4000/v1/categories/1/deactivate HTTP/1.1
Host: localhost:4000