name: ci-golang-workflow
on: [push]
jobs:
  check-application:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkouts@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.23
      - run: go test